### ISSUE TITLE
该项目被主流杀毒软件报病毒

### ISSUE THREAD

**Issue by zdm2008** [privch/privoxy-windows#1]
该项目编译的exe程序被主流杀毒软件报病毒，开发人员可以向这些杀毒厂商提交误报反馈。

360（需中国手机）:
https://open.soft.360.cn/report.php

金山：
https://www.ijinshan.com/virus_report/

瑞星（需登录账户）：
https://data.rising.com.cn/

Microsoft:
https://www.microsoft.com/en-us/wdsi/filesubmission

Norton:
https://symsubmit.symantec.com/

AVG:
https://www.avg.com/en-us/false-positive-file-form

Avast:
https://www.avast.com/false-positive-file-form.php

McAfee:
https://www.mcafee.com/enterprise/en-us/threat-center/detection-dispute-form.html

卡巴斯基:
https://opentip.kaspersky.com/

F-Secure:
https://www.f-secure.com/en/business/support-and-downloads/submit-a-sample

SecureAge APEX:
https://www.secureaplus.com/zh-tw/features/antivirus/report-false-positive/

Avira:
https://www.avira.com/en/analysis/submit

**Comment by xinlake** [comment]
> 该项目编译的exe程序被主流杀毒软件报病毒，开发人员可以向这些杀毒厂商提交误报反馈。
> 
> 360（需中国手机）:
> https://open.soft.360.cn/report.php
> 
> 金山：
> https://www.ijinshan.com/virus_report/
> 
> 瑞星（需登录账户）：
> https://data.rising.com.cn/
> 
> Microsoft:
> https://www.microsoft.com/en-us/wdsi/filesubmission
> 
> Norton:
> https://symsubmit.symantec.com/
> 
> AVG:
> https://www.avg.com/en-us/false-positive-file-form
> 
> Avast:
> https://www.avast.com/false-positive-file-form.php
> 
> McAfee:
> https://www.mcafee.com/enterprise/en-us/threat-center/detection-dispute-form.html
> 
> 卡巴斯基:
> https://opentip.kaspersky.com/
> 
> F-Secure:
> https://www.f-secure.com/en/business/support-and-downloads/submit-a-sample
> 
> SecureAge APEX:
> https://www.secureaplus.com/zh-tw/features/antivirus/report-false-positive/
> 
> Avira:
> https://www.avira.com/en/analysis/submit

你好，能提供一下杀毒软件报告的内容么？

**Comment by zdm2008** [comment]
![image](https://raw.githubusercontent.com/zdm2008/acme-tiny/master/360-proxy.png)

**Comment by xinlake** [comment]
@zdm2008 好的，这个问题会被优先处理，如果有其它杀毒软件报告安全问题也欢迎添加反馈。

**Comment by xinlake** [comment]
@zdm2008 你好，360已经解除了该项目exe木马病毒弹出提示。感谢你的反馈，有其他问题也欢迎随时issue。

**Comment by zdm2008** [comment]
经测试64位exe是没问题了，但是32位的exe任然报病毒，具体信息如下图。

![image](https://raw.githubusercontent.com/zdm2008/acme-tiny/master/360-proxy-32.png)

**Comment by zdm2008** [comment]
截止测试前，已经升级过最新的病毒库
